#
# Copyright (C) 2023 Ready.io
#

language = "C"
no_includes = true

[export]
item_types = ["functions"]

[fn]
args = "horizontal"
sort_by = "Name"
rename_args = "camelCase"

[parse]
parse_deps = true
include = []
extra_bindings = ["lib-messaging-bridge"]

[parse.expand]
crates = ["lib-messaging-jni", "lib-messaging-bridge"]
features = ["lib-messaging-bridge/jni"] #, "libsignal-bridge/signal-media"
